/* DOCS v1 start */
/* The research registry. Edit here (src/docs.js), then run tools/sync.py to copy into every page.
   Paths are derived, never stored: pdf = proof/research/<slug>.pdf, page i = proof/research/<slug>-pNN.jpg. */
const LINES = {
  role: { short: "Investment Research & Product Growth Strategist, Gotrade", anchor: "analyst.html#gotrade" },
  advisory: { short: "Advises clients above $100k AUM with catalyst-driven equity research", anchor: "analyst.html#gotrade" },
  alpha: { short: "Runs the Monthly Alpha Selection Book", anchor: "analyst.html#gotrade" },
  maybank: { short: "Written buy call on ATIC at Rp438, Dec 2024", anchor: "analyst.html#maybank" }
};
const ENGINE_LABEL = { "catalyst-projection-valuation": "CPV", "cpv-core": "cpv-core", "gotrade-ic-note": "gotrade-ic-note", "moat-analyzer": "moat-analyzer", "energy-macro-pack": "energy-macro-pack", "energy-sector-analysis": "energy-sector-analysis", "stock-writeup-composer": "stock-writeup-composer", "stock-writeup-pdf": "stock-writeup-pdf", "dhany-writeup-composer": "dhany-writeup-composer", "dhany-writeup-pdf": "dhany-writeup-pdf", "energy-refresh": "energy-refresh", "energy-read": "energy-read", "weekly-market-note": "weekly-market-note" };
const WRITEUP_ENGINES = ["moat-analyzer", "energy-macro-pack", "energy-sector-analysis", "cpv-core", "stock-writeup-composer", "stock-writeup-pdf"];
const DOCS = [
  { slug: "aph-ic-note", title: "Margin durability, not catalysts", ticker: "APH", company: "Amphenol", kind: "ic-note", kindLabel: "IC note", series: "ic", sector: "Tech hardware", date: "2026-08-27", pages: 12, format: "pdf", status: "final", attached: true, rendered: 12, rating: { entrant: "Weak Buy", holder: "Hold" }, spot: 161.34, pv: 170.15, currency: "$", thesis: "The in-window catalyst book is below the materiality gate, so what carries value is the operating margin near 29% and the 27.5x forward multiple. The one-year roll the prior bank dropped is worth $24.77 a share.", engines: ["catalyst-projection-valuation", "gotrade-ic-note"], lineage: "CPV v4.8 → gotrade-ic-note", line: "advisory", companion: "aph-ic-1pager" },
  { slug: "aph-ic-1pager", title: "IC summary, one page", ticker: "APH", company: "Amphenol", kind: "one-pager", kindLabel: "One-pager", series: "ic", sector: "Tech hardware", date: "2026-08-27", pages: 1, format: "pdf", status: "final", attached: true, rendered: 1, rating: { entrant: "Weak Buy", holder: "Hold" }, spot: 161.34, pv: 170.15, currency: "$", thesis: "The Amphenol IC note projected onto one page: the call, the distribution, the kill switches.", engines: ["catalyst-projection-valuation", "gotrade-ic-note"], lineage: "CPV v4.8 → gotrade-ic-note", line: "advisory", companion: "aph-ic-note" },
  { slug: "tel-ic-note", title: "Margin plus multiple, not catalysts", ticker: "TEL", company: "TE Connectivity", kind: "ic-note", kindLabel: "IC note", series: "ic", sector: "Tech hardware", date: "2026-08-27", pages: 11, format: "pdf", status: "final", attached: true, rendered: 11, rating: { entrant: "Weak Buy", holder: "Hold" }, spot: 205.03, pv: 210.40, currency: "$", thesis: "In-window catalyst revenue is 1.76% of base, below the materiality gate; the value carriers are the 22.2% adjusted margin and the 16.4x forward multiple. The FY2027 consensus makes the horizon check independent for the first time.", engines: ["catalyst-projection-valuation", "gotrade-ic-note"], lineage: "CPV v4.8 → gotrade-ic-note", line: "advisory", companion: "tel-ic-1pager" },
  { slug: "tel-ic-1pager", title: "IC summary, one page", ticker: "TEL", company: "TE Connectivity", kind: "one-pager", kindLabel: "One-pager", series: "ic", sector: "Tech hardware", date: "2026-08-27", pages: 1, format: "pdf", status: "final", attached: true, rendered: 1, rating: { entrant: "Weak Buy", holder: "Hold" }, spot: 205.03, pv: 210.40, currency: "$", thesis: "The TE Connectivity IC note projected onto one page: the call, the distribution, the kill switches.", engines: ["catalyst-projection-valuation", "gotrade-ic-note"], lineage: "CPV v4.8 → gotrade-ic-note", line: "advisory", companion: "tel-ic-note" },
  { slug: "nvda-ic-note", title: "The year the multiple is not paying for", ticker: "NVDA", company: "NVIDIA", kind: "ic-note", kindLabel: "IC note", series: "ic", sector: "Semis", date: "2026-09-02", pages: 26, format: "pdf", status: "final", attached: false, rendered: 0, rating: { entrant: "Strong Buy", holder: "Strong Hold" }, spot: 217.44, pv: 270.32, currency: "$", thesis: "The market pays 18x for the next twelve months of earnings and nothing for the year after. Held at that multiple the base case is worth $331 at exit; probability-weighted and discounted, $270.", engines: ["catalyst-projection-valuation", "gotrade-ic-note"], lineage: "CPV v4.10 → gotrade-ic-note", line: "advisory", companion: "nvda-ic-1pager" },
  { slug: "nvda-ic-1pager", title: "One-page summary", ticker: "NVDA", company: "NVIDIA", kind: "one-pager", kindLabel: "One-pager", series: "ic", sector: "Semis", date: "2026-09-02", pages: 1, format: "pdf", status: "final", attached: false, rendered: 0, rating: { entrant: "Strong Buy", holder: "Strong Hold" }, spot: 217.44, pv: 270.32, currency: "$", thesis: "The NVIDIA IC note projected onto one page.", engines: ["catalyst-projection-valuation", "gotrade-ic-note"], lineage: "CPV v4.10 → gotrade-ic-note", line: "advisory", companion: "nvda-ic-note" },
  { slug: "bkr-ic-note", title: "Catalyst, projection and implied valuation", ticker: "BKR", company: "Baker Hughes", kind: "ic-note", kindLabel: "IC note", series: "ic", sector: "Energy services", date: "2026-09-04", pages: 23, format: "pdf", status: "final", attached: false, rendered: 0, rating: { entrant: "No Buy", holder: "Hold" }, spot: 63.64, pv: 68.71, currency: "$", thesis: "The catalysts are real and immaterial. What decides the stock is the multiple paid for a larger, more industrial, more indebted earnings stream, and whether Chart's pre-deal profit survives consolidation. Conviction 2.5 of five.", engines: ["catalyst-projection-valuation", "gotrade-ic-note"], lineage: "CPV v4.10 → gotrade-ic-note", line: "advisory", companion: "bkr-ic-1pager" },
  { slug: "bkr-ic-1pager", title: "One page", ticker: "BKR", company: "Baker Hughes", kind: "one-pager", kindLabel: "One-pager", series: "ic", sector: "Energy services", date: "2026-09-04", pages: 1, format: "pdf", status: "final", attached: false, rendered: 0, rating: { entrant: "No Buy", holder: "Hold" }, spot: 63.64, pv: 68.71, currency: "$", thesis: "The Baker Hughes IC note projected onto one page.", engines: ["catalyst-projection-valuation", "gotrade-ic-note"], lineage: "CPV v4.10 → gotrade-ic-note", line: "advisory", companion: "bkr-ic-note" },
  { slug: "cnq-writeup", title: "Company analysis, financial performance and investment plan", ticker: "CNQ", company: "Canadian Natural Resources", kind: "writeup", kindLabel: "Write-up", series: "energy", sector: "Energy", date: "2026-09-10", pages: 8, format: "pdf", status: "final", attached: false, rendered: 0, rating: null, spot: null, pv: null, currency: "$", thesis: "Canadian Natural Resources in the three-stage house format.", engines: WRITEUP_ENGINES, lineage: "stock-writeup-composer → stock-writeup-pdf", line: "advisory", companion: null },
  { slug: "cop-writeup", title: "Company analysis, financial performance and investment plan", ticker: "COP", company: "ConocoPhillips", kind: "writeup", kindLabel: "Write-up", series: "energy", sector: "Energy", date: "2026-09-10", pages: 7, format: "pdf", status: "final", attached: false, rendered: 0, rating: null, spot: null, pv: null, currency: "$", thesis: "ConocoPhillips in the three-stage house format.", engines: WRITEUP_ENGINES, lineage: "stock-writeup-composer → stock-writeup-pdf", line: "advisory", companion: null },
  { slug: "cve-writeup", title: "Company analysis, financial performance and investment plan", ticker: "CVE", company: "Cenovus Energy", kind: "writeup", kindLabel: "Write-up", series: "energy", sector: "Energy", date: "2026-09-10", pages: 9, format: "pdf", status: "final", attached: false, rendered: 0, rating: null, spot: null, pv: null, currency: "$", thesis: "Cenovus Energy in the three-stage house format.", engines: WRITEUP_ENGINES, lineage: "stock-writeup-composer → stock-writeup-pdf", line: "advisory", companion: null },
  { slug: "cvx-writeup", title: "Company analysis, financial performance and investment plan", ticker: "CVX", company: "Chevron", kind: "writeup", kindLabel: "Write-up", series: "energy", sector: "Energy", date: "2026-09-15", pages: 34, format: "pdf", status: "final", attached: false, rendered: 0, rating: null, spot: null, pv: null, currency: "$", thesis: "Chevron in the three-stage house format, with the valuation and investment plan stages and the energy store read of 14 September 2026.", engines: WRITEUP_ENGINES, lineage: "stock-writeup-composer → stock-writeup-pdf", line: "advisory", companion: null },
  { slug: "fang-writeup", title: "Company analysis, financial performance and investment plan", ticker: "FANG", company: "Diamondback Energy", kind: "writeup", kindLabel: "Write-up", series: "energy", sector: "Energy", date: "2026-09-23", pages: 38, format: "pdf", status: "draft", attached: false, rendered: 0, rating: null, spot: null, pv: null, currency: "$", thesis: "Diamondback Energy in the three-stage house format.", engines: WRITEUP_ENGINES, lineage: "stock-writeup-composer → stock-writeup-pdf", line: "advisory", companion: null },
  { slug: "mpc-writeup", title: "Company analysis, financial performance and investment plan", ticker: "MPC", company: "Marathon Petroleum", kind: "writeup", kindLabel: "Write-up", series: "energy", sector: "Energy", date: "2026-09-23", pages: 32, format: "pdf", status: "draft", attached: false, rendered: 0, rating: null, spot: null, pv: null, currency: "$", thesis: "Marathon Petroleum in the three-stage house format.", engines: WRITEUP_ENGINES, lineage: "stock-writeup-composer → stock-writeup-pdf", line: "advisory", companion: null },
  { slug: "oxy-writeup", title: "Company analysis, financial performance and investment plan", ticker: "OXY", company: "Occidental Petroleum", kind: "writeup", kindLabel: "Write-up", series: "energy", sector: "Energy", date: "2026-09-23", pages: 35, format: "pdf", status: "draft", attached: false, rendered: 0, rating: null, spot: null, pv: null, currency: "$", thesis: "Occidental Petroleum in the three-stage house format.", engines: WRITEUP_ENGINES, lineage: "stock-writeup-composer → stock-writeup-pdf", line: "advisory", companion: null },
  { slug: "shel-writeup", title: "Company analysis, financial performance and investment plan", ticker: "SHEL", company: "Shell", kind: "writeup", kindLabel: "Write-up", series: "energy", sector: "Energy", date: "2026-09-23", pages: 41, format: "pdf", status: "draft", attached: false, rendered: 0, rating: null, spot: null, pv: null, currency: "$", thesis: "Shell in the three-stage house format.", engines: WRITEUP_ENGINES, lineage: "stock-writeup-composer → stock-writeup-pdf", line: "advisory", companion: null },
  { slug: "adbe-research", title: "Undervalued, but AI execution must deliver", ticker: "ADBE", company: "Adobe", kind: "editorial", kindLabel: "Editorial", series: "editorial", sector: "Software", date: "2026-09-16", pages: 10, format: "pdf", status: "final", attached: false, rendered: 0, rating: null, spot: null, pv: null, currency: "$", thesis: "A high-quality subscription business with AI-first ARR above $650 million; the case turns on Firefly deepening workflow ownership.", engines: ["dhany-writeup-composer", "dhany-writeup-pdf"], lineage: "dhany-writeup-composer → dhany-writeup-pdf", line: "advisory", companion: null },
  { slug: "house-format-sample", title: "A dependable subscription business, priced for a margin recovery it has not yet shown", ticker: "MLSW", company: "Meridian Ledger Software (worked example)", kind: "editorial", kindLabel: "Editorial", series: "editorial", sector: "Software", date: "2026-09-29", pages: 6, format: "pdf", status: "sample", attached: true, rendered: 6, rating: null, spot: null, pv: null, currency: "$", thesis: "The Gotrade Research editorial format demonstrated on a worked-example company: research view, base-case DCF with scenarios, the questions that decide the case, risks and a disclosures page.", engines: ["dhany-writeup-composer", "dhany-writeup-pdf"], lineage: "dhany-writeup-composer → dhany-writeup-pdf", line: "role", companion: null },
  { slug: "weekly-note-2026-09-27", title: "Weekly Market Note, 21–27 September 2026, oil edition", ticker: "", company: "", kind: "weekly", kindLabel: "Weekly note", series: "weekly", sector: "Macro", date: "2026-09-27", pages: 12, format: "pdf", status: "final", attached: true, rendered: 12, rating: null, spot: null, pv: null, currency: "$", thesis: "Brent dips below $100 and recovers as Saudi Arabia reopens its pipeline. Prices, flows through Hormuz, inventories and what the futures curve is pricing, with every figure sourced and dated.", engines: ["energy-refresh", "energy-read", "weekly-market-note"], lineage: "energy store → weekly-market-note", line: "role", companion: null },
  { slug: "weekly-note-2026-09-20", title: "Weekly Market Note, 14–20 September 2026", ticker: "", company: "", kind: "weekly", kindLabel: "Weekly note", series: "weekly", sector: "Macro", date: "2026-09-20", pages: 12, format: "pdf", status: "final", attached: false, rendered: 0, rating: null, spot: null, pv: null, currency: "$", thesis: "Rate hikes in Washington and Tokyo, a hold in London: three central bank decisions in three days and the bond market's reply.", engines: ["weekly-market-note"], lineage: "weekly-market-note", line: "role", companion: null },
  { slug: "atic-note", title: "Buy call, December 2024", ticker: "ATIC", company: "PT Anabatic Technologies", kind: "archive", kindLabel: "Archive", series: "archive", sector: "Indonesia", date: "2024-12-02", pages: 7, format: "pdf", status: "final", attached: true, rendered: 7, rating: null, spot: null, pv: null, currency: "Rp", thesis: "Written on the morning of 2 December 2024 at Rp378; the buy was called at Rp438 and a client position of $273k exited at Rp835 within the year, +91% against +22% for the IHSG in 2025.", engines: [], lineage: "Maybank Securities Indonesia", line: "maybank", companion: null, byline: "Prepared by Faldo Lyon, Equity Research Analyst Intern, Maybank Securities Indonesia" }
];
const SERIES = [
  { key: "ic", title: "IC notes", sub: "catalyst-projection-valuation → gotrade-ic-note" },
  { key: "energy", title: "Energy write-ups", sub: "three-stage house format" },
  { key: "editorial", title: "Editorial", sub: "Gotrade Research format" },
  { key: "weekly", title: "Weekly Market Note", sub: "from the energy store" },
  { key: "archive", title: "Archive", sub: "Maybank Securities Indonesia" }
];
/* ---- pure helpers (no DOM access at load) ---- */
const esc = (s) => String(s ?? "").replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c]));
const pad2 = (n) => String(n).padStart(2, "0");
const docPaths = (d) => ({
  pdf: "proof/research/" + d.slug + ".pdf",
  cover: "proof/research/" + d.slug + "-p01.jpg",
  page: (i) => "proof/research/" + d.slug + "-p" + pad2(i) + ".jpg",
  pages: Array.from({ length: d.rendered || 0 }, (_, i) => ({ file: "proof/research/" + d.slug + "-p" + pad2(i + 1) + ".jpg", cap: (d.ticker || d.kindLabel) + " · page " + (i + 1) + " of " + d.pages }))
});
const docBySlug = (slug) => DOCS.find((d) => d.slug === slug) || null;
const upside = (d) => (d.spot && d.pv) ? ((d.pv / d.spot - 1) * 100) : null;
const fmtUpside = (d) => { const u = upside(d); return u === null ? "" : (u >= 0 ? "+" : "") + u.toFixed(1) + "%"; };
const fmtPx = (d) => d.spot && d.pv ? `${d.currency}${d.spot.toFixed(2)} → ${d.currency}${d.pv.toFixed(2)} · ${fmtUpside(d)}` : "";
const MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
const fmtDate = (iso) => { const [y, m, d] = iso.split("-").map(Number); return `${d} ${MONTHS[m - 1]} ${y}`; };
const fmtMonth = (iso) => { const [y, m] = iso.split("-").map(Number); return `${MONTHS[m - 1]} ${y}`; };
const stampList = (d) => [d.status === "draft" ? "Draft · not for distribution" : d.status === "sample" ? "Sample · worked example" : null, d.attached === false ? "To be attached" : null].filter(Boolean);
const statusLabel = (d) => [d.status === "draft" ? "Draft" : d.status === "sample" ? "Sample" : null, d.attached === false ? "To be attached" : null].filter(Boolean).join(" · ") || "Final";
const stampText = (d) => stampList(d).join(" · ");
const statusSentence = (d) => [d.status === "draft" ? "This document is a draft stamped NOT FOR DISTRIBUTION; figures may change." : d.status === "sample" ? "The subject is a worked-example company used to demonstrate the format, not a live recommendation." : null, d.attached === false ? "The PDF has not been attached yet; the metadata is from the document itself." : null].filter(Boolean).join(" ");
const metaLine = (d) => [d.ticker || d.kindLabel.toUpperCase(), d.ticker ? d.kindLabel.toUpperCase() : null, fmtDate(d.date).toUpperCase(), d.format === "html" ? "HTML" : d.pages + " PP"].filter(Boolean).join(" · ");
const ratingHTML = (d) => d.rating ? `<div class="rating"><span class="chip ent" title="Rating for new money (the engine's entrant rating)">New money · ${esc(d.rating.entrant)}</span><span class="chip hol" title="Rating for existing holders (the engine's holder rating)">Holders · ${esc(d.rating.holder)}</span>${fmtPx(d) ? `<span class="px num" title="Spot price → probability-weighted fair value · upside">${esc(fmtPx(d))}</span>` : ""}</div>` : `<div class="rating"><span class="none">Rating: see document</span></div>`;
const lineageHTML = (d) => `<div class="lineage mono">${d.engines.length ? d.engines.map((e) => `<a href="engines.html#${esc(e)}" style="color:inherit;text-decoration:none">${esc(ENGINE_LABEL[e] || e)}</a>`).join(" → ") : esc(d.lineage)}</div>`;
const provesHTML = (d) => `<div class="proves mono">Proves: <a href="${esc(LINES[d.line].anchor)}">${esc(LINES[d.line].short)}</a></div>`;
/* docCard(d, {open}) where open is 'pane' (same page, #doc=) or 'research' (link to research.html#doc=). */
const docCard = (d, opts = {}) => {
  const p = docPaths(d), live = d.attached !== false, href = (opts.open === "research" ? "research.html" : "") + "#doc=" + d.slug;
  const stamp = stampList(d).map((t) => `<span class="stamp">${esc(t)}</span>`).join("");
  const cover = live
    ? `<span class="cover"><img src="${esc(p.cover)}" alt="${esc(d.company || d.title)}, page 1" loading="lazy" decoding="async" width="1000" height="1414" onerror="this.parentNode.className='cover empty';this.parentNode.innerHTML='<b>${esc(d.ticker || d.kindLabel)}</b><i>${esc(d.kindLabel)}</i>';this.closest('.doc').classList.add('slot')">${stamp}</span>`
    : `<span class="cover empty"><b>${esc(d.ticker || d.kindLabel)}</b><i>${esc(d.kindLabel)}</i>${stamp}</span>`;
  const openBtn = opts.open === "research"
    ? `<a class="doc-open" href="${esc(href)}" ${live ? "" : 'aria-disabled="true"'}>${cover}</a>`
    : `<button class="doc-open" type="button" data-doc="${esc(d.slug)}" ${live ? "" : 'aria-disabled="true"'}>${cover}</button>`;
  return `<article class="doc${live ? "" : " slot"}" data-slug="${esc(d.slug)}">${openBtn}<div class="meta mono">${esc(metaLine(d))}</div><h3 class="ttl"><a href="${esc(href)}" data-doc="${esc(d.slug)}">${esc(d.title)}</a></h3>${ratingHTML(d)}${lineageHTML(d)}${provesHTML(d)}<p class="thesis">${esc(d.thesis)}</p></article>`;
};
const totals = (docs = DOCS) => ({
  count: docs.length,
  pages: docs.reduce((s, d) => s + (d.pages || 0), 0),
  attached: docs.filter((d) => d.attached !== false).length,
  first: docs.map((d) => d.date).sort()[0],
  last: docs.map((d) => d.date).sort().slice(-1)[0],
  names: new Set(docs.filter((d) => d.ticker && d.status !== "sample").map((d) => d.ticker)).size
});
/* DOCS v1 end */
